// generated by stringer -type=Frob; DO NOT EDIT

package main

import "fmt"

const _Frob_name = "MeowWoofRibbit"

var _Frob_index = [...]uint8{4, 8, 14}

func (i Frob) String() string {
	if i < 0 || i >= Frob(len(_Frob_index)) {
		return fmt.Sprintf("Frob(%d)", i)
	}
	hi := _Frob_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _Frob_index[i-1]
	}
	return _Frob_name[lo:hi]
}
